# TODO: we need to simplify our lint config.  we should aim to follow the
# standards set by the react-app & airbnb configs if we intend to use them
# at all! :)  AirBnB has a good config, but they tend to change it now and
# again as React is updated and libs, styles, and conventions are improved
# so it's often good to follow their lead, which also reduces overhead for
# us :).  For now, think i have this working _mostly_ with existing bloom-
# portal lint rules, but we should try to tackle these rules one at a time
# per PR (over time of course).
extends:
  - "./node_modules/eslint-config-react-app/index.js"
  - react-app
  - airbnb
  - "plugin:import/errors"
  - "plugin:import/warnings"
rules:
  strict: 0
  semi:
    - 2
    - never
  react/jsx-filename-extension: 0
  no-console: 1
  no-debugger: 1
  react/require-default-props: 0
   # forbid-prop-types: default adds forbid-object, currently 92 errors
   #    could do this later on with better knowledge of data?
   #    for styles use styleProp: PropTypes.objectOf(PropTypes.oneOfType([PropTypes.string, PropTypes.number])),
  react/forbid-prop-types:
    - 2
    - forbid:
      - any
      - array
  jsx-a11y/label-has-for: 0
  jsx-a11y/no-static-element-interactions: 0
  lodash/import-scope:
    - 2
    - member
  react/jsx-curly-brace-presence: 0 # TODO: enable?
  function-paren-newline:
    - 2
    - consistent
  jsx-a11y/anchor-is-valid: 0 # TODON'T - wants hrefs - we don't use links - has problem with Links
  object-curly-newline:
    - 2
    - consistent: true
  jsx-a11y/click-events-have-key-events: 0 # TODO: enable!
env:
  browser: true
  jest: true
globals:
  __webpack_hash__: true
plugins:
  - react
  - lodash
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
settings:
  import/parser: babel-eslint
  import/ignore:
    - node_modules
    - assets
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src/
