import { initializePriceRows, zipPriceRows } from './priceGroup'

export const pricesObj = {
  prices: [{
    customerType: 'RECREATIONAL',
    portalActive: true,
    price: { amount: '5.99', currency: 'USD' },
    quantityAmount: 1,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'MEDICAL',
    portalActive: true,
    price: { amount: '5.99', currency: 'USD' },
    quantityAmount: 1,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'RECREATIONAL',
    portalActive: false,
    price: { amount: '11.98', currency: 'USD' },
    quantityAmount: 2,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'MEDICAL',
    portalActive: false,
    price: { amount: '11.98', currency: 'USD' },
    quantityAmount: 2,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'RECREATIONAL',
    portalActive: false,
    price: { amount: '20.97', currency: 'USD' },
    quantityAmount: 3.5,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'MEDICAL',
    portalActive: true,
    price: { amount: '14.99', currency: 'USD' },
    quantityAmount: 3.5,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'RECREATIONAL',
    portalActive: true,
    price: { amount: '20.00', currency: 'USD' },
    quantityAmount: 7,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'MEDICAL',
    portalActive: false,
    price: { amount: '29.98', currency: 'USD' },
    quantityAmount: 7,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'RECREATIONAL',
    portalActive: false,
    price: { amount: '40.00', currency: 'USD' },
    quantityAmount: 14,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'MEDICAL',
    portalActive: false,
    price: { amount: '59.96', currency: 'USD' },
    quantityAmount: 14,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'RECREATIONAL',
    portalActive: false,
    price: { amount: '80.00', currency: 'USD' },
    quantityAmount: 28,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }, {
    customerType: 'MEDICAL',
    portalActive: false,
    price: { amount: '119.92', currency: 'USD' },
    quantityAmount: 28,
    quantityUnit: 'GRAMS',
    volumeAmount: null,
    volumeUnit: 'MILLILITERS',
    __typename: 'Price',
  }],
}

export const customPGPreTax = {
  prices: {
    rec: [{
      portalActive: true,
      post: '9.18',
      pre: '5.99',
      quantityAmount: 1,
      quantityUnit: 'GRAMS',
      tax: '3.19',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '16.37',
      pre: '11.98',
      quantityAmount: 2,
      quantityUnit: 'GRAMS',
      tax: '4.39',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '27.16',
      pre: '20.97',
      quantityAmount: 3.5,
      quantityUnit: 'GRAMS',
      tax: '6.19',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: true,
      post: '26.00',
      pre: '20.00',
      quantityAmount: 7,
      quantityUnit: 'GRAMS',
      tax: '6.00',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '50.00',
      pre: '40.00',
      quantityAmount: 14,
      quantityUnit: 'GRAMS',
      tax: '10.00',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '98.00',
      pre: '80.00',
      quantityAmount: 28,
      quantityUnit: 'GRAMS',
      tax: '18.00',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }],
    med: [{
      portalActive: true,
      post: '6.58',
      pre: '5.99',
      quantityAmount: 1,
      quantityUnit: 'GRAMS',
      tax: '0.59',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '13.17',
      pre: '11.98',
      quantityAmount: 2,
      quantityUnit: 'GRAMS',
      tax: '1.19',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: true,
      post: '16.48',
      pre: '14.99',
      quantityAmount: 3.5,
      quantityUnit: 'GRAMS',
      tax: '1.49',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '32.97',
      pre: '29.98',
      quantityAmount: 7,
      quantityUnit: 'GRAMS',
      tax: '2.99',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '65.95',
      pre: '59.96',
      quantityAmount: 14,
      quantityUnit: 'GRAMS',
      tax: '5.99',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '131.91',
      pre: '119.92',
      quantityAmount: 28,
      quantityUnit: 'GRAMS',
      tax: '11.99',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }],
  },
}

const customPGPostTax = {
  prices: {
    rec: [{
      portalActive: true,
      post: '5.99',
      pre: '3.33',
      quantityAmount: 1,
      quantityUnit: 'GRAMS',
      tax: '2.66',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '11.98',
      pre: '8.32',
      quantityAmount: 2,
      quantityUnit: 'GRAMS',
      tax: '3.66',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '20.97',
      pre: '15.81',
      quantityAmount: 3.5,
      quantityUnit: 'GRAMS',
      tax: '5.16',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: true,
      post: '20.00',
      pre: '15.00',
      quantityAmount: 7,
      quantityUnit: 'GRAMS',
      tax: '5.00',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '40.00',
      pre: '31.67',
      quantityAmount: 14,
      quantityUnit: 'GRAMS',
      tax: '8.33',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '80.00',
      pre: '65.00',
      quantityAmount: 28,
      quantityUnit: 'GRAMS',
      tax: '15.00',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }],
    med: [{
      portalActive: true,
      post: '5.99',
      pre: '5.45',
      quantityAmount: 1,
      quantityUnit: 'GRAMS',
      tax: '0.54',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '11.98',
      pre: '10.90',
      quantityAmount: 2,
      quantityUnit: 'GRAMS',
      tax: '1.08',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: true,
      post: '14.99',
      pre: '13.63',
      quantityAmount: 3.5,
      quantityUnit: 'GRAMS',
      tax: '1.36',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '29.98',
      pre: '27.26',
      quantityAmount: 7,
      quantityUnit: 'GRAMS',
      tax: '2.72',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '59.96',
      pre: '54.51',
      quantityAmount: 14,
      quantityUnit: 'GRAMS',
      tax: '5.45',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }, {
      portalActive: false,
      post: '119.92',
      pre: '109.02',
      quantityAmount: 28,
      quantityUnit: 'GRAMS',
      tax: '10.90',
      volumeAmount: null,
      volumeUnit: 'MILLILITERS',
      __typename: 'Price',
    }],
  },
}

const zippedPrices = [
  {
    customerType: 'RECREATIONAL',
    portalActive: true,
    price: '5.99',
    quantityAmount: 1,
    volumeAmount: null,
  }, {
    customerType: 'RECREATIONAL',
    portalActive: false,
    price: '11.98',
    quantityAmount: 2,
    volumeAmount: null,
  }, {
    customerType: 'RECREATIONAL',
    portalActive: false,
    price: '20.97',
    quantityAmount: 3.5,
    volumeAmount: null,
  }, {
    customerType: 'RECREATIONAL',
    portalActive: true,
    price: '20.00',
    quantityAmount: 7,
    volumeAmount: null,
  }, {
    customerType: 'RECREATIONAL',
    portalActive: false,
    price: '40.00',
    quantityAmount: 14,
    volumeAmount: null,
  }, {
    customerType: 'RECREATIONAL',
    portalActive: false,
    price: '80.00',
    quantityAmount: 28,
    volumeAmount: null,
  }, {
    customerType: 'MEDICAL',
    portalActive: true,
    price: '5.99',
    quantityAmount: 1,
    volumeAmount: null,
  }, {
    customerType: 'MEDICAL',
    portalActive: false,
    price: '11.98',
    quantityAmount: 2,
    volumeAmount: null,
  }, {
    customerType: 'MEDICAL',
    portalActive: true,
    price: '14.99',
    quantityAmount: 3.5,
    volumeAmount: null,
  }, {
    customerType: 'MEDICAL',
    portalActive: false,
    price: '29.98',
    quantityAmount: 7,
    volumeAmount: null,
  }, {
    customerType: 'MEDICAL',
    portalActive: false,
    price: '59.96',
    quantityAmount: 14,
    volumeAmount: null,
  }, {
    customerType: 'MEDICAL',
    portalActive: false,
    price: '119.92',
    quantityAmount: 28,
    volumeAmount: null,
  },
]

const taxObj = {
  rec: {
    percentage: 0.2,
    fixed: 2,
  },
  med: {
    percentage: 0.1,
    fixed: 0,
  },
}

describe('initializePriceRows', () => {
  // PRE-TAX
  test('Returns the rec and med prices given a price object', () => {
    const { prices } = initializePriceRows(Object.assign({}, pricesObj), taxObj, true)
    expect(prices).toEqual(customPGPreTax.prices)
  })
  // POST-TAX
  test('Returns the rec and med prices given a price object', () => {
    const { prices } = initializePriceRows(Object.assign({}, pricesObj), taxObj, false)
    expect(prices).toEqual(customPGPostTax.prices)
  })
})

describe('zipPriceRows', () => {
  // PRE-TAX
  test('Returns a price group object given the rec and med prices', () => {
    const prices = zipPriceRows(true, customPGPreTax)
    expect(prices).toEqual(zippedPrices)
  })
  // POST-TAX
  test('Returns a price group object given the rec and med prices', () => {
    const prices = zipPriceRows(false, customPGPostTax)
    expect(prices).toEqual(zippedPrices)
  })
})
